# Generated by Django 4.2 on 2023-04-16 16:02

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_aadhar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='aadhar',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
