# Generated by Django 4.2 on 2023-04-16 19:18

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_address_alter_profile_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='aadhar',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[users.models.validate_aadhaar_number]),
        ),
    ]
